
CREATE TABLE Contacts (
    CID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Phone VARCHAR(255) NOT NULL,
    Faculty VARCHAR(255) NOT NULL
);
