
CREATE TABLE Programs (
    PID INT AUTO_INCREMENT PRIMARY KEY,
    EID INT,
    PName VARCHAR(255) NOT NULL,
    PTime TIME NOT NULL,
    PLocation VARCHAR(255),
    PType VARCHAR(100),
    PImage VARCHAR(255),
    PStartDate DATETIME NOT NULL,
    PEndDate DATETIME NOT NULL,
    PDecription TEXT,
    PDF VARCHAR(255),
    Fee DECIMAL(10, 2),
    Min INT,
    Max INT,
    Contact INT,
    CID INT,
    Open BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (EID) REFERENCES Events(EID),
    FOREIGN KEY (CID) REFERENCES Coordinators(CID)
);
